### PR TITLE
Fixes #255

### LINKED ISSUE #255: VaadinSharedSecurity ignored sessionAuthenticationStrategy failures
While using ConcurrentSessionControlAuthenticationStrategy or other, authentication can fail after successful authentication due to max. session count etc. But VaadinSharedSecurity assign authentication to context after Manager authentication, to after ```sessionAuthenticationStrategy```.

I get max. session error on login page, but if I remove the login link, it access to the page, because authentication is already set to context.

        try {
            logger.debug("Attempting authentication of {}, rememberMe = {}", authentication, rememberMe);
            final Authentication fullyAuthenticated = getAuthenticationManager().authenticate(authentication);
            context.setAuthentication(fullyAuthenticated);
            if (rememberMe) {
                if (hasRememberMeServices()) {
                    logger.debug("Invoking RememberMeServices");
                    getRememberMeServices().loginSuccess(request, response, authentication);
                } else {
                    throw new IllegalStateException("Requested RememberMe authentication but no RememberBeServices are available");
                }
            }
            logger.debug("Invoking session authentication strategy");
            sessionAuthenticationStrategy.onAuthentication(fullyAuthenticated, request, response);
            logger.debug("Invoking authentication success handler");
            vaadinAuthenticationSuccessHandler.onAuthenticationSuccess(fullyAuthenticated);
            return authentication;
        } catch (AuthenticationException e) {
            logger.debug("Authentication failed");
            context = SecurityContextHolder.createEmptyContext();
            if (hasRememberMeServices()) {
                logger.debug("Invoking RememberMeServices");
                getRememberMeServices().loginFail(request, response);
            }
            throw e;
        }
so
 - ```context.setAuthentication(fullyAuthenticated);``` and rememeberMe check needs to be moved after ```sessionAuthenticationStrategy```check
- catch should set authentication to null, instead of setting context to null.

Please see ```AbstractAuthenticationProcessingFilter``` implementation, spring-security call this normally.

### PR DESCRIPTION
**Pull request by GJRTimmer**
Rewrote according to comments of @gokhanoner

See comments in code.

### CODE REVIEW

File: extensions/security/src/main/java/org/vaadin/spring/security/internal/VaadinSharedSecurity.java [hunk 1]
```diff
@@ -73,6 +73,45 @@ public Authentication login(Authentication authentication, boolean rememberMe) t
...
+                if (hasRememberMeServices()) {
+                    logger.debug("Invoking RememberMeServices");
+                    getRememberMeServices().loginFail(request, response);
+                }
+                
+                /* 
+                 * Return NULL
+                 * And set {@link Autentication} object reference to NULL
+                 */
+                authentication = null;
```
Comment (peholmst) [inline extensions/security/src/main/java/org/vaadin/spring/security/internal/VaadinSharedSecurity.java]: Shouldn't this be null already?
